# Generated by Django 5.1 on 2024-08-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_desc', models.TextField()),
                ('full_desc', models.TextField()),
                ('image_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('views', models.IntegerField()),
                ('category', models.ManyToManyField(to='main.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
